parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger: none

jobs:
- job: build
  displayName: build

  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
  - task: SystemsManagerRunCommand@1
    inputs:
      regionName: 'us-east-1'
      documentName: 'AWS-RunPowerShellScript'
      serviceRoleARN: 'arn:aws:iam::486077440167:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
      instanceSelector: 'fromInstanceIds'
      instanceIds: 'i-0f9b9ebd2bd80c22a'
      documentParameters: '{"commands":["Enable-WindowsOptionalFeature –online –featurename IIS-WebServerRole"]}'
      
