# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-2022
  - ubuntu-latest
trigger:
- main

pool:
  vmImage: $image

steps:
- script: echo Hello,  $(userName1)!
  displayName: 'Run a one-line script'

- task: PowerShell@2
  inputs:    
    targetType: filePath
    filePath: $(Build.SourcesDirectory)\test.ps1        
    
  

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
