parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger: none

jobs:
- job: build
  displayName: build

  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
  - task: SystemsManagerRunCommand@1
    inputs:
      regionName: 'us-east-1'
      documentName: 'AWS-RunShellScript'
      serviceRoleARN: 'arn:aws:iam::486077440167:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
      instanceSelector: 'fromInstanceIds'
      instanceIds: 'i-018f5a57a80b12dbf'
      documentParameters: '{"commands":["curl \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\"","unzip awscliv2.zip","aws s3 cp s3://nucodedeplytestapplication/Index2.html /usr/share/nginx/html/"]}'
      