parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger: none

jobs:
- job: build
  displayName: build

  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}

  - task: SystemsManagerRunCommand@1
    inputs:
      regionName: 'us-east-1'
      documentName: 'AWS-RunPowerShellScript'
      documentParameters: '{"commands":["exit","aws s3 cp s3://nucodedeplytestapplication/azure-pipelines55.zip C:\\Web"]}'
      instanceSelector: 'fromInstanceIds'
      instanceIds: 'i-0f9b9ebd2bd80c22a'
      logRequest: true
      logResponse: true
    
    
