# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - nitin udasin
  - Ashoo
trigger:
- main

pool:
  vmImage: windows-2022

steps:
- script: echo Hello,  $(userName1)!
  displayName: 'Run a one-line script'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: my-arm-service-connection
    scriptType: filePath
    scriptPath: $(Build.SourcesDirectory)\test.ps1    
    azurePowerShellVersion: latestVersion
    pwsh: true
  

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
