parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest

trigger: none

jobs:
- job: build
  displayName: build

  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }}
    
  - task: AWSCLI@1
    inputs:
      regionName: 'us-east-1'
      awsCommand: 'aws s3 cp s3://nucodedeplytestapplication/azure-pipelines55.zip C:\\Web'
      failOnStandardError: true
  - task: SystemsManagerRunCommand@1
    inputs:
      regionName: 'us-east-1'
      documentName: 'AWS-RunPowerShellScript'
      documentParameters: '{"commands":["cd c:\\Web",".\\test.ps1"]}'
      instanceSelector: 'fromInstanceIds'
      instanceIds: 'i-0f9b9ebd2bd80c22a'
      outputS3BucketName: 'nucodedeplytestapplication'
      outputS3KeyPrefix: 'cmdlogs_'
      logRequest: true
      logResponse: true
  
    
    
